/**
 * OpenWeatherMap Client
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.mallorcasoftware.openweatherclient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * CurrentWeatherDataResponseWindDto
 */

public class CurrentWeatherDataResponseWindDto   {
  @SerializedName("speed")
  private Double speed = null;

  @SerializedName("deg")
  private Integer deg = null;

  public CurrentWeatherDataResponseWindDto speed(Double speed) {
    this.speed = speed;
    return this;
  }

   /**
   * Get speed
   * @return speed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getSpeed() {
    return speed;
  }

  public void setSpeed(Double speed) {
    this.speed = speed;
  }

  public CurrentWeatherDataResponseWindDto deg(Integer deg) {
    this.deg = deg;
    return this;
  }

   /**
   * Get deg
   * @return deg
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDeg() {
    return deg;
  }

  public void setDeg(Integer deg) {
    this.deg = deg;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CurrentWeatherDataResponseWindDto currentWeatherDataResponseWindDto = (CurrentWeatherDataResponseWindDto) o;
    return Objects.equals(this.speed, currentWeatherDataResponseWindDto.speed) &&
        Objects.equals(this.deg, currentWeatherDataResponseWindDto.deg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(speed, deg);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrentWeatherDataResponseWindDto {\n");
    
    sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
    sb.append("    deg: ").append(toIndentedString(deg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

