/**
 * OpenWeatherMap Client
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.mallorcasoftware.openweatherclient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.mallorcasoftware.openweatherclient.model.CurrentWeatherDataResponseCloudsDto;
import com.mallorcasoftware.openweatherclient.model.CurrentWeatherDataResponseMainDto;
import com.mallorcasoftware.openweatherclient.model.CurrentWeatherDataResponseRainDto;
import com.mallorcasoftware.openweatherclient.model.CurrentWeatherDataResponseSnowDto;
import com.mallorcasoftware.openweatherclient.model.CurrentWeatherDataResponseSysDto;
import com.mallorcasoftware.openweatherclient.model.CurrentWeatherDataResponseWeatherDto;
import com.mallorcasoftware.openweatherclient.model.CurrentWeatherDataResponseWindDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * CurrentWeatherDataResponse
 */

public class CurrentWeatherDataResponse   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("visibility")
  private Integer visibility = null;

  @SerializedName("weather")
  private List<CurrentWeatherDataResponseWeatherDto> weather = new ArrayList<CurrentWeatherDataResponseWeatherDto>();

  @SerializedName("main")
  private CurrentWeatherDataResponseMainDto main = null;

  @SerializedName("wind")
  private CurrentWeatherDataResponseWindDto wind = null;

  @SerializedName("clouds")
  private CurrentWeatherDataResponseCloudsDto clouds = null;

  @SerializedName("rain")
  private CurrentWeatherDataResponseRainDto rain = null;

  @SerializedName("snow")
  private CurrentWeatherDataResponseSnowDto snow = null;

  @SerializedName("sys")
  private CurrentWeatherDataResponseSysDto sys = null;

  @SerializedName("dt")
  private String dt = null;

  public CurrentWeatherDataResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CurrentWeatherDataResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CurrentWeatherDataResponse visibility(Integer visibility) {
    this.visibility = visibility;
    return this;
  }

   /**
   * Get visibility
   * @return visibility
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getVisibility() {
    return visibility;
  }

  public void setVisibility(Integer visibility) {
    this.visibility = visibility;
  }

  public CurrentWeatherDataResponse weather(List<CurrentWeatherDataResponseWeatherDto> weather) {
    this.weather = weather;
    return this;
  }

  public CurrentWeatherDataResponse addWeatherItem(CurrentWeatherDataResponseWeatherDto weatherItem) {
    this.weather.add(weatherItem);
    return this;
  }

   /**
   * Get weather
   * @return weather
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<CurrentWeatherDataResponseWeatherDto> getWeather() {
    return weather;
  }

  public void setWeather(List<CurrentWeatherDataResponseWeatherDto> weather) {
    this.weather = weather;
  }

  public CurrentWeatherDataResponse main(CurrentWeatherDataResponseMainDto main) {
    this.main = main;
    return this;
  }

   /**
   * Get main
   * @return main
  **/
  @ApiModelProperty(example = "null", value = "")
  public CurrentWeatherDataResponseMainDto getMain() {
    return main;
  }

  public void setMain(CurrentWeatherDataResponseMainDto main) {
    this.main = main;
  }

  public CurrentWeatherDataResponse wind(CurrentWeatherDataResponseWindDto wind) {
    this.wind = wind;
    return this;
  }

   /**
   * Get wind
   * @return wind
  **/
  @ApiModelProperty(example = "null", value = "")
  public CurrentWeatherDataResponseWindDto getWind() {
    return wind;
  }

  public void setWind(CurrentWeatherDataResponseWindDto wind) {
    this.wind = wind;
  }

  public CurrentWeatherDataResponse clouds(CurrentWeatherDataResponseCloudsDto clouds) {
    this.clouds = clouds;
    return this;
  }

   /**
   * Get clouds
   * @return clouds
  **/
  @ApiModelProperty(example = "null", value = "")
  public CurrentWeatherDataResponseCloudsDto getClouds() {
    return clouds;
  }

  public void setClouds(CurrentWeatherDataResponseCloudsDto clouds) {
    this.clouds = clouds;
  }

  public CurrentWeatherDataResponse rain(CurrentWeatherDataResponseRainDto rain) {
    this.rain = rain;
    return this;
  }

   /**
   * Get rain
   * @return rain
  **/
  @ApiModelProperty(example = "null", value = "")
  public CurrentWeatherDataResponseRainDto getRain() {
    return rain;
  }

  public void setRain(CurrentWeatherDataResponseRainDto rain) {
    this.rain = rain;
  }

  public CurrentWeatherDataResponse snow(CurrentWeatherDataResponseSnowDto snow) {
    this.snow = snow;
    return this;
  }

   /**
   * Get snow
   * @return snow
  **/
  @ApiModelProperty(example = "null", value = "")
  public CurrentWeatherDataResponseSnowDto getSnow() {
    return snow;
  }

  public void setSnow(CurrentWeatherDataResponseSnowDto snow) {
    this.snow = snow;
  }

  public CurrentWeatherDataResponse sys(CurrentWeatherDataResponseSysDto sys) {
    this.sys = sys;
    return this;
  }

   /**
   * Get sys
   * @return sys
  **/
  @ApiModelProperty(example = "null", value = "")
  public CurrentWeatherDataResponseSysDto getSys() {
    return sys;
  }

  public void setSys(CurrentWeatherDataResponseSysDto sys) {
    this.sys = sys;
  }

  public CurrentWeatherDataResponse dt(String dt) {
    this.dt = dt;
    return this;
  }

   /**
   * Get dt
   * @return dt
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDt() {
    return dt;
  }

  public void setDt(String dt) {
    this.dt = dt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CurrentWeatherDataResponse currentWeatherDataResponse = (CurrentWeatherDataResponse) o;
    return Objects.equals(this.id, currentWeatherDataResponse.id) &&
        Objects.equals(this.name, currentWeatherDataResponse.name) &&
        Objects.equals(this.visibility, currentWeatherDataResponse.visibility) &&
        Objects.equals(this.weather, currentWeatherDataResponse.weather) &&
        Objects.equals(this.main, currentWeatherDataResponse.main) &&
        Objects.equals(this.wind, currentWeatherDataResponse.wind) &&
        Objects.equals(this.clouds, currentWeatherDataResponse.clouds) &&
        Objects.equals(this.rain, currentWeatherDataResponse.rain) &&
        Objects.equals(this.snow, currentWeatherDataResponse.snow) &&
        Objects.equals(this.sys, currentWeatherDataResponse.sys) &&
        Objects.equals(this.dt, currentWeatherDataResponse.dt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, visibility, weather, main, wind, clouds, rain, snow, sys, dt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrentWeatherDataResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    weather: ").append(toIndentedString(weather)).append("\n");
    sb.append("    main: ").append(toIndentedString(main)).append("\n");
    sb.append("    wind: ").append(toIndentedString(wind)).append("\n");
    sb.append("    clouds: ").append(toIndentedString(clouds)).append("\n");
    sb.append("    rain: ").append(toIndentedString(rain)).append("\n");
    sb.append("    snow: ").append(toIndentedString(snow)).append("\n");
    sb.append("    sys: ").append(toIndentedString(sys)).append("\n");
    sb.append("    dt: ").append(toIndentedString(dt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

