/**
 * OpenWeatherMap Client
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.mallorcasoftware.openweatherclient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * CurrentWeatherDataResponseWeatherDto
 */

public class CurrentWeatherDataResponseWeatherDto   {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("main")
  private String main = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("icon")
  private String icon = null;

  public CurrentWeatherDataResponseWeatherDto id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public CurrentWeatherDataResponseWeatherDto main(String main) {
    this.main = main;
    return this;
  }

   /**
   * Get main
   * @return main
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMain() {
    return main;
  }

  public void setMain(String main) {
    this.main = main;
  }

  public CurrentWeatherDataResponseWeatherDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CurrentWeatherDataResponseWeatherDto icon(String icon) {
    this.icon = icon;
    return this;
  }

   /**
   * Get icon
   * @return icon
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIcon() {
    return icon;
  }

  public void setIcon(String icon) {
    this.icon = icon;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CurrentWeatherDataResponseWeatherDto currentWeatherDataResponseWeatherDto = (CurrentWeatherDataResponseWeatherDto) o;
    return Objects.equals(this.id, currentWeatherDataResponseWeatherDto.id) &&
        Objects.equals(this.main, currentWeatherDataResponseWeatherDto.main) &&
        Objects.equals(this.description, currentWeatherDataResponseWeatherDto.description) &&
        Objects.equals(this.icon, currentWeatherDataResponseWeatherDto.icon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, main, description, icon);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrentWeatherDataResponseWeatherDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    main: ").append(toIndentedString(main)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

